services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Divante\UserBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Divante\UserBundle\Service\UserService: ~
